// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/kv-storage.proto

package kv_storage_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Operation     *string                `protobuf:"bytes,3,opt,name=operation,proto3,oneof" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetRequest) GetOperation() string {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{3}
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GossipRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLeader      bool                   `protobuf:"varint,1,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{5}
}

func (x *GossipResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

type LeaderVoteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CandidateAddress string                 `protobuf:"bytes,1,opt,name=candidate_address,json=candidateAddress,proto3" json:"candidate_address,omitempty"`
	Term             int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeaderVoteRequest) Reset() {
	*x = LeaderVoteRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderVoteRequest) ProtoMessage() {}

func (x *LeaderVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderVoteRequest.ProtoReflect.Descriptor instead.
func (*LeaderVoteRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{6}
}

func (x *LeaderVoteRequest) GetCandidateAddress() string {
	if x != nil {
		return x.CandidateAddress
	}
	return ""
}

func (x *LeaderVoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type LeaderVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteGranted   bool                   `protobuf:"varint,1,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderVoteResponse) Reset() {
	*x = LeaderVoteResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderVoteResponse) ProtoMessage() {}

func (x *LeaderVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderVoteResponse.ProtoReflect.Descriptor instead.
func (*LeaderVoteResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *LeaderVoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type FetchFromSeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFromSeedRequest) Reset() {
	*x = FetchFromSeedRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFromSeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFromSeedRequest) ProtoMessage() {}

func (x *FetchFromSeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFromSeedRequest.ProtoReflect.Descriptor instead.
func (*FetchFromSeedRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{8}
}

func (x *FetchFromSeedRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FetchFromSeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []string               `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFromSeedResponse) Reset() {
	*x = FetchFromSeedResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFromSeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFromSeedResponse) ProtoMessage() {}

func (x *FetchFromSeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFromSeedResponse.ProtoReflect.Descriptor instead.
func (*FetchFromSeedResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{9}
}

func (x *FetchFromSeedResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type LeMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeMetaRequest) Reset() {
	*x = LeMetaRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeMetaRequest) ProtoMessage() {}

func (x *LeMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeMetaRequest.ProtoReflect.Descriptor instead.
func (*LeMetaRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{10}
}

type LeMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          int64                  `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	DataVersion   int64                  `protobuf:"varint,2,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeMetaResponse) Reset() {
	*x = LeMetaResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeMetaResponse) ProtoMessage() {}

func (x *LeMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeMetaResponse.ProtoReflect.Descriptor instead.
func (*LeMetaResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{11}
}

func (x *LeMetaResponse) GetNode() int64 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *LeMetaResponse) GetDataVersion() int64 {
	if x != nil {
		return x.DataVersion
	}
	return 0
}

type UpdateLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeaderRequest) Reset() {
	*x = UpdateLeaderRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeaderRequest) ProtoMessage() {}

func (x *UpdateLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeaderRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeaderRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateLeaderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLeaderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeaderResponse) Reset() {
	*x = UpdateLeaderResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeaderResponse) ProtoMessage() {}

func (x *UpdateLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeaderResponse.ProtoReflect.Descriptor instead.
func (*UpdateLeaderResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateLeaderResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type UpdateAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressesRequest) Reset() {
	*x = UpdateAddressesRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressesRequest) ProtoMessage() {}

func (x *UpdateAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressesRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressesRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{14}
}

type UpdateAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressesResponse) Reset() {
	*x = UpdateAddressesResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressesResponse) ProtoMessage() {}

func (x *UpdateAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressesResponse.ProtoReflect.Descriptor instead.
func (*UpdateAddressesResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{15}
}

var File_api_kv_storage_proto protoreflect.FileDescriptor

const file_api_kv_storage_proto_rawDesc = "" +
	"\n" +
	"\x14api/kv-storage.proto\x12\x12kv_storage_service\x1a\x19google/protobuf/any.proto\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"e\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12!\n" +
	"\toperation\x18\x03 \x01(\tH\x00R\toperation\x88\x01\x01B\f\n" +
	"\n" +
	"_operation\"\r\n" +
	"\vSetResponse\"#\n" +
	"\rGossipRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"-\n" +
	"\x0eGossipResponse\x12\x1b\n" +
	"\tis_leader\x18\x01 \x01(\bR\bisLeader\"T\n" +
	"\x11LeaderVoteRequest\x12+\n" +
	"\x11candidate_address\x18\x01 \x01(\tR\x10candidateAddress\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\"K\n" +
	"\x12LeaderVoteResponse\x12!\n" +
	"\fvote_granted\x18\x01 \x01(\bR\vvoteGranted\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\"0\n" +
	"\x14FetchFromSeedRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"-\n" +
	"\x15FetchFromSeedResponse\x12\x14\n" +
	"\x05peers\x18\x01 \x03(\tR\x05peers\"\x0f\n" +
	"\rLeMetaRequest\"G\n" +
	"\x0eLeMetaResponse\x12\x12\n" +
	"\x04node\x18\x01 \x01(\x03R\x04node\x12!\n" +
	"\fdata_version\x18\x02 \x01(\x03R\vdataVersion\"?\n" +
	"\x13UpdateLeaderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"4\n" +
	"\x14UpdateLeaderResponse\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"\x18\n" +
	"\x16UpdateAddressesRequest\"\x19\n" +
	"\x17UpdateAddressesResponse2\xca\x05\n" +
	"\x0fKeyValueStorage\x12F\n" +
	"\x03Get\x12\x1e.kv_storage_service.GetRequest\x1a\x1f.kv_storage_service.GetResponse\x12F\n" +
	"\x03Set\x12\x1e.kv_storage_service.SetRequest\x1a\x1f.kv_storage_service.SetResponse\x12P\n" +
	"\tSetStream\x12\x1e.kv_storage_service.SetRequest\x1a\x1f.kv_storage_service.SetResponse(\x010\x01\x12O\n" +
	"\x06Gossip\x12!.kv_storage_service.GossipRequest\x1a\".kv_storage_service.GossipResponse\x12d\n" +
	"\rFetchFromSeed\x12(.kv_storage_service.FetchFromSeedRequest\x1a).kv_storage_service.FetchFromSeedResponse\x12O\n" +
	"\x06LeMeta\x12!.kv_storage_service.LeMetaRequest\x1a\".kv_storage_service.LeMetaResponse\x12a\n" +
	"\fUpdateLeader\x12'.kv_storage_service.UpdateLeaderRequest\x1a(.kv_storage_service.UpdateLeaderResponse\x12j\n" +
	"\x0fUpdateAddresses\x12*.kv_storage_service.UpdateAddressesRequest\x1a+.kv_storage_service.UpdateAddressesResponseBQZOgithub.com/Na322Pr/kv-storage-service/pkg/kv-storage-service;kv_storage_serviceb\x06proto3"

var (
	file_api_kv_storage_proto_rawDescOnce sync.Once
	file_api_kv_storage_proto_rawDescData []byte
)

func file_api_kv_storage_proto_rawDescGZIP() []byte {
	file_api_kv_storage_proto_rawDescOnce.Do(func() {
		file_api_kv_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kv_storage_proto_rawDesc), len(file_api_kv_storage_proto_rawDesc)))
	})
	return file_api_kv_storage_proto_rawDescData
}

var file_api_kv_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_kv_storage_proto_goTypes = []any{
	(*GetRequest)(nil),              // 0: kv_storage_service.GetRequest
	(*GetResponse)(nil),             // 1: kv_storage_service.GetResponse
	(*SetRequest)(nil),              // 2: kv_storage_service.SetRequest
	(*SetResponse)(nil),             // 3: kv_storage_service.SetResponse
	(*GossipRequest)(nil),           // 4: kv_storage_service.GossipRequest
	(*GossipResponse)(nil),          // 5: kv_storage_service.GossipResponse
	(*LeaderVoteRequest)(nil),       // 6: kv_storage_service.LeaderVoteRequest
	(*LeaderVoteResponse)(nil),      // 7: kv_storage_service.LeaderVoteResponse
	(*FetchFromSeedRequest)(nil),    // 8: kv_storage_service.FetchFromSeedRequest
	(*FetchFromSeedResponse)(nil),   // 9: kv_storage_service.FetchFromSeedResponse
	(*LeMetaRequest)(nil),           // 10: kv_storage_service.LeMetaRequest
	(*LeMetaResponse)(nil),          // 11: kv_storage_service.LeMetaResponse
	(*UpdateLeaderRequest)(nil),     // 12: kv_storage_service.UpdateLeaderRequest
	(*UpdateLeaderResponse)(nil),    // 13: kv_storage_service.UpdateLeaderResponse
	(*UpdateAddressesRequest)(nil),  // 14: kv_storage_service.UpdateAddressesRequest
	(*UpdateAddressesResponse)(nil), // 15: kv_storage_service.UpdateAddressesResponse
}
var file_api_kv_storage_proto_depIdxs = []int32{
	0,  // 0: kv_storage_service.KeyValueStorage.Get:input_type -> kv_storage_service.GetRequest
	2,  // 1: kv_storage_service.KeyValueStorage.Set:input_type -> kv_storage_service.SetRequest
	2,  // 2: kv_storage_service.KeyValueStorage.SetStream:input_type -> kv_storage_service.SetRequest
	4,  // 3: kv_storage_service.KeyValueStorage.Gossip:input_type -> kv_storage_service.GossipRequest
	8,  // 4: kv_storage_service.KeyValueStorage.FetchFromSeed:input_type -> kv_storage_service.FetchFromSeedRequest
	10, // 5: kv_storage_service.KeyValueStorage.LeMeta:input_type -> kv_storage_service.LeMetaRequest
	12, // 6: kv_storage_service.KeyValueStorage.UpdateLeader:input_type -> kv_storage_service.UpdateLeaderRequest
	14, // 7: kv_storage_service.KeyValueStorage.UpdateAddresses:input_type -> kv_storage_service.UpdateAddressesRequest
	1,  // 8: kv_storage_service.KeyValueStorage.Get:output_type -> kv_storage_service.GetResponse
	3,  // 9: kv_storage_service.KeyValueStorage.Set:output_type -> kv_storage_service.SetResponse
	3,  // 10: kv_storage_service.KeyValueStorage.SetStream:output_type -> kv_storage_service.SetResponse
	5,  // 11: kv_storage_service.KeyValueStorage.Gossip:output_type -> kv_storage_service.GossipResponse
	9,  // 12: kv_storage_service.KeyValueStorage.FetchFromSeed:output_type -> kv_storage_service.FetchFromSeedResponse
	11, // 13: kv_storage_service.KeyValueStorage.LeMeta:output_type -> kv_storage_service.LeMetaResponse
	13, // 14: kv_storage_service.KeyValueStorage.UpdateLeader:output_type -> kv_storage_service.UpdateLeaderResponse
	15, // 15: kv_storage_service.KeyValueStorage.UpdateAddresses:output_type -> kv_storage_service.UpdateAddressesResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_kv_storage_proto_init() }
func file_api_kv_storage_proto_init() {
	if File_api_kv_storage_proto != nil {
		return
	}
	file_api_kv_storage_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kv_storage_proto_rawDesc), len(file_api_kv_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kv_storage_proto_goTypes,
		DependencyIndexes: file_api_kv_storage_proto_depIdxs,
		MessageInfos:      file_api_kv_storage_proto_msgTypes,
	}.Build()
	File_api_kv_storage_proto = out.File
	file_api_kv_storage_proto_goTypes = nil
	file_api_kv_storage_proto_depIdxs = nil
}
