// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/kv-storage.proto

package kv_storage_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GossipRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLeader      bool                   `protobuf:"varint,1,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{5}
}

func (x *GossipResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

type LeaderVoteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CandidateAddress string                 `protobuf:"bytes,1,opt,name=candidate_address,json=candidateAddress,proto3" json:"candidate_address,omitempty"`
	Term             int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeaderVoteRequest) Reset() {
	*x = LeaderVoteRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderVoteRequest) ProtoMessage() {}

func (x *LeaderVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderVoteRequest.ProtoReflect.Descriptor instead.
func (*LeaderVoteRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{6}
}

func (x *LeaderVoteRequest) GetCandidateAddress() string {
	if x != nil {
		return x.CandidateAddress
	}
	return ""
}

func (x *LeaderVoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type LeaderVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteGranted   bool                   `protobuf:"varint,1,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderVoteResponse) Reset() {
	*x = LeaderVoteResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderVoteResponse) ProtoMessage() {}

func (x *LeaderVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderVoteResponse.ProtoReflect.Descriptor instead.
func (*LeaderVoteResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *LeaderVoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type FetchFromSeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFromSeedRequest) Reset() {
	*x = FetchFromSeedRequest{}
	mi := &file_api_kv_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFromSeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFromSeedRequest) ProtoMessage() {}

func (x *FetchFromSeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFromSeedRequest.ProtoReflect.Descriptor instead.
func (*FetchFromSeedRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{8}
}

func (x *FetchFromSeedRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FetchFromSeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []string               `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFromSeedResponse) Reset() {
	*x = FetchFromSeedResponse{}
	mi := &file_api_kv_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFromSeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFromSeedResponse) ProtoMessage() {}

func (x *FetchFromSeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFromSeedResponse.ProtoReflect.Descriptor instead.
func (*FetchFromSeedResponse) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{9}
}

func (x *FetchFromSeedResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_kv_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_kv_storage_proto_rawDescGZIP(), []int{10}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_kv_storage_proto protoreflect.FileDescriptor

const file_api_kv_storage_proto_rawDesc = "" +
	"\n" +
	"\x14api/kv-storage.proto\x12\x12kv_storage_service\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\rGossipRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"-\n" +
	"\x0eGossipResponse\x12\x1b\n" +
	"\tis_leader\x18\x01 \x01(\bR\bisLeader\"T\n" +
	"\x11LeaderVoteRequest\x12+\n" +
	"\x11candidate_address\x18\x01 \x01(\tR\x10candidateAddress\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\"K\n" +
	"\x12LeaderVoteResponse\x12!\n" +
	"\fvote_granted\x18\x01 \x01(\bR\vvoteGranted\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\"0\n" +
	"\x14FetchFromSeedRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"-\n" +
	"\x15FetchFromSeedResponse\x12\x14\n" +
	"\x05peers\x18\x01 \x03(\tR\x05peers\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb5\x03\n" +
	"\x0fKeyValueStorage\x12F\n" +
	"\x03Get\x12\x1e.kv_storage_service.GetRequest\x1a\x1f.kv_storage_service.GetResponse\x12F\n" +
	"\x03Set\x12\x1e.kv_storage_service.SetRequest\x1a\x1f.kv_storage_service.SetResponse\x12O\n" +
	"\x06Gossip\x12!.kv_storage_service.GossipRequest\x1a\".kv_storage_service.GossipResponse\x12[\n" +
	"\n" +
	"LeaderVote\x12%.kv_storage_service.LeaderVoteRequest\x1a&.kv_storage_service.LeaderVoteResponse\x12d\n" +
	"\rFetchFromSeed\x12(.kv_storage_service.FetchFromSeedRequest\x1a).kv_storage_service.FetchFromSeedResponseBaZ_github.com/Na322Pr/key-value-store/kv-storage-service/pkg/kv-storage-service;kv_storage_serviceb\x06proto3"

var (
	file_api_kv_storage_proto_rawDescOnce sync.Once
	file_api_kv_storage_proto_rawDescData []byte
)

func file_api_kv_storage_proto_rawDescGZIP() []byte {
	file_api_kv_storage_proto_rawDescOnce.Do(func() {
		file_api_kv_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kv_storage_proto_rawDesc), len(file_api_kv_storage_proto_rawDesc)))
	})
	return file_api_kv_storage_proto_rawDescData
}

var file_api_kv_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_kv_storage_proto_goTypes = []any{
	(*GetRequest)(nil),            // 0: kv_storage_service.GetRequest
	(*GetResponse)(nil),           // 1: kv_storage_service.GetResponse
	(*SetRequest)(nil),            // 2: kv_storage_service.SetRequest
	(*SetResponse)(nil),           // 3: kv_storage_service.SetResponse
	(*GossipRequest)(nil),         // 4: kv_storage_service.GossipRequest
	(*GossipResponse)(nil),        // 5: kv_storage_service.GossipResponse
	(*LeaderVoteRequest)(nil),     // 6: kv_storage_service.LeaderVoteRequest
	(*LeaderVoteResponse)(nil),    // 7: kv_storage_service.LeaderVoteResponse
	(*FetchFromSeedRequest)(nil),  // 8: kv_storage_service.FetchFromSeedRequest
	(*FetchFromSeedResponse)(nil), // 9: kv_storage_service.FetchFromSeedResponse
	(*Status)(nil),                // 10: kv_storage_service.Status
}
var file_api_kv_storage_proto_depIdxs = []int32{
	0, // 0: kv_storage_service.KeyValueStorage.Get:input_type -> kv_storage_service.GetRequest
	2, // 1: kv_storage_service.KeyValueStorage.Set:input_type -> kv_storage_service.SetRequest
	4, // 2: kv_storage_service.KeyValueStorage.Gossip:input_type -> kv_storage_service.GossipRequest
	6, // 3: kv_storage_service.KeyValueStorage.LeaderVote:input_type -> kv_storage_service.LeaderVoteRequest
	8, // 4: kv_storage_service.KeyValueStorage.FetchFromSeed:input_type -> kv_storage_service.FetchFromSeedRequest
	1, // 5: kv_storage_service.KeyValueStorage.Get:output_type -> kv_storage_service.GetResponse
	3, // 6: kv_storage_service.KeyValueStorage.Set:output_type -> kv_storage_service.SetResponse
	5, // 7: kv_storage_service.KeyValueStorage.Gossip:output_type -> kv_storage_service.GossipResponse
	7, // 8: kv_storage_service.KeyValueStorage.LeaderVote:output_type -> kv_storage_service.LeaderVoteResponse
	9, // 9: kv_storage_service.KeyValueStorage.FetchFromSeed:output_type -> kv_storage_service.FetchFromSeedResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kv_storage_proto_init() }
func file_api_kv_storage_proto_init() {
	if File_api_kv_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kv_storage_proto_rawDesc), len(file_api_kv_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kv_storage_proto_goTypes,
		DependencyIndexes: file_api_kv_storage_proto_depIdxs,
		MessageInfos:      file_api_kv_storage_proto_msgTypes,
	}.Build()
	File_api_kv_storage_proto = out.File
	file_api_kv_storage_proto_goTypes = nil
	file_api_kv_storage_proto_depIdxs = nil
}
